sudo: required
services:
  - docker

before_install:
  - docker build -t dhinesh04/docker-react -f Dockerfile.dev1 .

script:
  - docker run -e CI=true dhinesh04/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-156041403531"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY